/**
 * omp, the default 16-bit style pixel-art mascot for models without their own character.
 *
 * A small slate-and-teal terminal-buddy robot with a screen face. Poses: idle/blink
 * for at rest, work1/work2/work-blink cycled while the agent is streaming (eyes
 * glance side to side, arms type, the antenna lamp and chest lights flicker),
 * happy briefly when a stream finishes (arc eyes, wide smile, arms raised).
 */
import type { PetPose, SpriteArt } from "./sprite";

const PALETTE: Record<string, string> = {
	o: "#1f2a36", // outline (dark slate)
	b: "#8fa4b8", // casing (slate)
	B: "#5f758c", // casing shade / feet
	l: "#c3d2e0", // casing highlight
	v: "#12202b", // screen (near black)
	g: "#3b5568", // screen glare
	c: "#2dd4bf", // eye / LED teal
	C: "#99f6e4", // eye / LED teal (bright)
	w: "#ffffff", // eye sparkle
	m: "#2dd4bf", // mouth / chest bar (teal)
	a: "#f59e0b", // antenna tip (amber)
	A: "#fde68a", // antenna tip (lit)
	k: "#f59e0b", // ear bolt / status lamp (amber)
};

const POSES: Record<PetPose, string[]> = {
	idle: [
		"................................",
		"..............oaao..............",
		"..............oaao..............",
		"...............oo...............",
		"...............oo...............",
		"........oooooooooooooooo........",
		".......obllllllllllllllbo.......",
		".......olbbbbbbbbbbbbbbBo.......",
		".......olooooooooooooooBo.......",
		"......oologgvvvvvvvvvvoBoo......",
		".....oBolovwccvvvvwccvoBoBo.....",
		".....okolovcccvvvvcccvoBoko.....",
		".....okolovcccvvvvcccvoBoko.....",
		".....oBolovCCCvvvvCCCvoBoBo.....",
		"......oolovvvvvvvvvvvvoBoo......",
		".......olovvvvmvvmvvvvoBo.......",
		".......olovvvvvmmvvvvvoBo.......",
		".......obooooooooooooooBo.......",
		".......obBBBBBBBBBBBBBBbo.......",
		"........oooooooooooooooo........",
		"...........oooooooooo...........",
		".......oo.ollllllllllo.oo.......",
		"......obboobbvvvvvvbboobbo......",
		"......obboobbvcCvkvbboobbo......",
		"......obboobbvvvvvvbboobbo......",
		"......olloobbvmmmmvbboollo......",
		".......oo.oBBBBBBBBBBo.oo.......",
		"...........oooooooooo...........",
		"...........oooo..oooo...........",
		"..........oBBBBooBBBBo..........",
		"...........oooo..oooo...........",
		"................................",
	],
	blink: [
		"................................",
		"..............oaao..............",
		"..............oaao..............",
		"...............oo...............",
		"...............oo...............",
		"........oooooooooooooooo........",
		".......obllllllllllllllbo.......",
		".......olbbbbbbbbbbbbbbBo.......",
		".......olooooooooooooooBo.......",
		"......oologgvvvvvvvvvvoBoo......",
		".....oBolovvvvvvvvvvvvoBoBo.....",
		".....okolovvvvvvvvvvvvoBoko.....",
		".....okolovcccvvvvcccvoBoko.....",
		".....oBolovvvvvvvvvvvvoBoBo.....",
		"......oolovvvvvvvvvvvvoBoo......",
		".......olovvvvmvvmvvvvoBo.......",
		".......olovvvvvmmvvvvvoBo.......",
		".......obooooooooooooooBo.......",
		".......obBBBBBBBBBBBBBBbo.......",
		"........oooooooooooooooo........",
		"...........oooooooooo...........",
		".......oo.ollllllllllo.oo.......",
		"......obboobbvvvvvvbboobbo......",
		"......obboobbvcCvkvbboobbo......",
		"......obboobbvvvvvvbboobbo......",
		"......olloobbvmmmmvbboollo......",
		".......oo.oBBBBBBBBBBo.oo.......",
		"...........oooooooooo...........",
		"...........oooo..oooo...........",
		"..........oBBBBooBBBBo..........",
		"...........oooo..oooo...........",
		"................................",
	],
	work1: [
		"................................",
		"..............oAAo..............",
		"..............oAAo..............",
		"...............oo...............",
		"...............oo...............",
		"........oooooooooooooooo........",
		".......obllllllllllllllbo.......",
		".......olbbbbbbbbbbbbbbBo.......",
		".......olooooooooooooooBo.......",
		"......oologgvvvvvvvvvvoBoo......",
		".....oBolowCCvvvvwCCvvoBoBo.....",
		".....okoloCCCvvvvCCCvvoBoko.....",
		".....okoloCCCvvvvCCCvvoBoko.....",
		".....oBoloCCCvvvvCCCvvoBoBo.....",
		"......oolovvvvvvvvvvvvoBoo......",
		".......olovvvvmvvmvvvvoBo.......",
		".......olovvvvvmmvvvvvoBo.......",
		".......obooooooooooooooBo.......",
		".......obBBBBBBBBBBBBBBbo.......",
		"........oooooooooooooooo........",
		".......oo..oooooooooo...........",
		"......obboollllllllllo..........",
		"......obboobbvvvvvvbbo.oo.......",
		"......olloobbvCCvAvbboobbo......",
		".......oo.obbvvvvvvbboobbo......",
		"..........obbvmmmmvbboobbo......",
		"..........oBBBBBBBBBBoollo......",
		"...........oooooooooo..oo.......",
		"...........oooo..oooo...........",
		"..........oBBBBooBBBBo..........",
		"...........oooo..oooo...........",
		"................................",
	],
	work2: [
		"................................",
		"..............oaao..............",
		"..............oaao..............",
		"...............oo...............",
		"...............oo...............",
		"........oooooooooooooooo........",
		".......obllllllllllllllbo.......",
		".......olbbbbbbbbbbbbbbBo.......",
		".......olooooooooooooooBo.......",
		"......oologgvvvvvvvvvvoBoo......",
		".....oBolovvwccvvvvwccoBoBo.....",
		".....okolovvcccvvvvcccoBoko.....",
		".....okolovvcccvvvvcccoBoko.....",
		".....oBolovvCCCvvvvCCCoBoBo.....",
		"......oolovvvvvvvvvvvvoBoo......",
		".......olovvvvmvvmvvvvoBo.......",
		".......olovvvvvmmvvvvvoBo.......",
		".......obooooooooooooooBo.......",
		".......obBBBBBBBBBBBBBBbo.......",
		"........oooooooooooooooo........",
		"...........oooooooooo..oo.......",
		"..........olllllllllloobbo......",
		".......oo.obbvvvvvvbboobbo......",
		"......obboobbvccvkvbboollo......",
		"......obboobbvvvvvvbbo.oo.......",
		"......obboobbvmmmmvbbo..........",
		"......ollooBBBBBBBBBBo..........",
		".......oo..oooooooooo...........",
		"...........oooo..oooo...........",
		"..........oBBBBooBBBBo..........",
		"...........oooo..oooo...........",
		"................................",
	],
	"work-blink": [
		"................................",
		"..............oAAo..............",
		"..............oAAo..............",
		"...............oo...............",
		"...............oo...............",
		"........oooooooooooooooo........",
		".......obllllllllllllllbo.......",
		".......olbbbbbbbbbbbbbbBo.......",
		".......olooooooooooooooBo.......",
		"......oologgvvvvvvvvvvoBoo......",
		".....oBolovvvvvvvvvvvvoBoBo.....",
		".....okolovvvvvvvvvvvvoBoko.....",
		".....okolovCCCvvvvCCCvoBoko.....",
		".....oBolovvvvvvvvvvvvoBoBo.....",
		"......oolovvvvvvvvvvvvoBoo......",
		".......olovvvvmvvmvvvvoBo.......",
		".......olovvvvvmmvvvvvoBo.......",
		".......obooooooooooooooBo.......",
		".......obBBBBBBBBBBBBBBbo.......",
		"........oooooooooooooooo........",
		".......oo..oooooooooo...........",
		"......obboollllllllllo..........",
		"......obboobbvvvvvvbbo.oo.......",
		"......olloobbvcCvkvbboobbo......",
		".......oo.obbvvvvvvbboobbo......",
		"..........obbvmmmmvbboobbo......",
		"..........oBBBBBBBBBBoollo......",
		"...........oooooooooo..oo.......",
		"...........oooo..oooo...........",
		"..........oBBBBooBBBBo..........",
		"...........oooo..oooo...........",
		"................................",
	],
	happy: [
		"................................",
		"..............oAAo..............",
		"..............oAAo..............",
		"...............oo...............",
		"...............oo...............",
		"........oooooooooooooooo........",
		".......obllllllllllllllbo.......",
		".......olbbbbbbbbbbbbbbBo.......",
		".......olooooooooooooooBo.......",
		"......oologgvvvvvvvvvvoBoo......",
		".....oBolovvvvvvvvvvvvoBoBo.....",
		".....okolovvCvvvvvvCvvoBoko.....",
		".....okolovCvCvvvvCvCvoBoko.....",
		".....oBolovvvvvvvvvvvvoBoBo.....",
		"......oolovvvmvvvvmvvvoBoo......",
		"....oo.olovvvmmmmmmvvvoBo.oo....",
		"...olloolovvvvmmmmvvvvoBoollo...",
		"...obboobooooooooooooooBoobbo...",
		"...obboobBBBBBBBBBBBBBBboobbo...",
		"...obbo.oooooooooooooooo.obbo...",
		"...obbooo..oooooooooo..ooobbo...",
		"...ollolloolllllllllloollollo...",
		"....oo.oo.obbvvvvvvbbo.oo.oo....",
		"..........obbvcCvkvbbo..........",
		"..........obbvvvvvvbbo..........",
		"..........obbvmmmmvbbo..........",
		"..........oBBBBBBBBBBo..........",
		"...........oooooooooo...........",
		"...........oooo..oooo...........",
		"..........oBBBBooBBBBo..........",
		"...........oooo..oooo...........",
		"................................",
	],
};

/** omp's pixel art (palette + poses) for the shared sprite engine. */
export const DEFAULT_SPRITE: SpriteArt = {
	palette: PALETTE,
	poses: POSES,
};
