/**
 * Opus, a 16-bit style pixel-art avatar for Claude Opus models.
 *
 * The elder scholar of the cast: a plump great horned owl with prominent ear
 * tufts, a round cream facial disc and large amber eyes ringed by thin dark
 * spectacles whose bridge sits over the little hooked beak. Clay-orange
 * plumage with shaded wing edges, a cream chest carrying chevron feather
 * marks and the Claude starburst, and talons gripping a closed book. Colored
 * after the warm Anthropic palette (clay #d97757, cream #f0eee6, dark brown
 * outline).
 *
 * Poses: idle/blink for at rest, work1/work2/work-blink cycled while the agent
 * is streaming (the signature owl head tilt, left then right, as if the bird
 * is pondering, pupils following the tilt), happy briefly when a stream
 * finishes (arc eyes, wings spread wide, ear tufts perked up).
 */
import type { PetPose, SpriteArt } from "./sprite";

const PALETTE: Record<string, string> = {
	o: "#3b2a22", // outline, pupils, spectacle frames (dark brown)
	r: "#d97757", // plumage (Claude clay)
	R: "#b05a3c", // plumage shade, wing and tuft edges
	c: "#f0eee6", // facial disc, chest, book pages (cream)
	d: "#d9d2bf", // chest chevron marks
	a: "#f0a878", // beak, talons, starburst core (warm amber)
	y: "#f4b942", // iris (bright amber)
	Y: "#c98a2b", // iris rim, beak tip (deep amber)
	g: "#ffffff", // eye sparkle
	b: "#7a4e36", // book cover
	B: "#5a3727", // book spine and shadow
};

const POSES: Record<PetPose, string[]> = {
	idle: [
		"................................",
		"................................",
		".......oo..............oo.......",
		"......oRro............orRo......",
		".....oRrro..oooooooo..orrRo.....",
		"....oRrrrooorrrrrrrrooorrrRo....",
		"....oRrrrrrrrrrrrrrrrrrrrrRo....",
		".....orrrrrrrrrrrrrrrrrrrro.....",
		"......orrrrrccccccccrrrrro......",
		".....orroooooccccccooooorro.....",
		"....orrocYYYcoccccocYYYcorro....",
		"....orroYyyyYooooooYyyyYorro....",
		"....orooYygoYoccccoYygoYooro....",
		"....orroYyooYocaacoYyooYorro....",
		"....orrocYYYcocYYcocYYYcorro....",
		".....orroooooccccccooooorro.....",
		"......orrccccccccccccccrro......",
		".......oorrrrrrrrrrrrrroo.......",
		".........ooorrccccrrooo.........",
		".........orrccccccccrro.........",
		"........oRrcccYaaYcccrRo........",
		"........oRrccYaaaaYccrRo........",
		"........oRrcccYaaYcccrRo........",
		".........oRrdcdccdcdrRo.........",
		"..........orrdccccdrro..........",
		"...........oorrrrrroo...........",
		"....oooooooaaaooooaaaooooooo....",
		"...obbbbbbbbbbbbbbbbbbbbbbbbo...",
		"...oBBcccccccccccccccccccccco...",
		"...oBBBBBBBBBBBBBBBBBBBBBBBBo...",
		"....oooooooooooooooooooooooo....",
		"................................",
	],
	blink: [
		"................................",
		"................................",
		".......oo..............oo.......",
		"......oRro............orRo......",
		".....oRrro..oooooooo..orrRo.....",
		"....oRrrrooorrrrrrrrooorrrRo....",
		"....oRrrrrrrrrrrrrrrrrrrrrRo....",
		".....orrrrrrrrrrrrrrrrrrrro.....",
		"......orrrrrccccccccrrrrro......",
		".....orroooooccccccooooorro.....",
		"....orrocccccoccccocccccorro....",
		"....orrocccccoooooocccccorro....",
		"....orooooooooccccooooooooro....",
		"....orrocccccocaacocccccorro....",
		"....orrocccccocYYcocccccorro....",
		".....orroooooccccccooooorro.....",
		"......orrccccccccccccccrro......",
		".......oorrrrrrrrrrrrrroo.......",
		".........ooorrccccrrooo.........",
		".........orrccccccccrro.........",
		"........oRrcccYaaYcccrRo........",
		"........oRrccYaaaaYccrRo........",
		"........oRrcccYaaYcccrRo........",
		".........oRrdcdccdcdrRo.........",
		"..........orrdccccdrro..........",
		"...........oorrrrrroo...........",
		"....oooooooaaaooooaaaooooooo....",
		"...obbbbbbbbbbbbbbbbbbbbbbbbo...",
		"...oBBcccccccccccccccccccccco...",
		"...oBBBBBBBBBBBBBBBBBBBBBBBBo...",
		"....oooooooooooooooooooooooo....",
		"................................",
	],
	work1: [
		"................................",
		"......oo........................",
		".....oRro.............oo........",
		"....oRrro............orRo.......",
		"...oRrrro..oooooooo..orrRo......",
		"...oRrrrroorrrrrrrrooorrrRo.....",
		"....orrrrrrrrrrrrrrrrrrrrRo.....",
		".....oorrrrrrrrrrrrrrrrrro......",
		".....orrrrrccccccccrrrrro.......",
		"....orrrccccccccccooooorro......",
		"...orrcooooocccccocYYYcorro.....",
		"...orrocYYYcoccccoYyyyYorro.....",
		"...orroYyyyYooooooYgoyYooro.....",
		"...orooYgoyYocaacoYooyYorro.....",
		"...orroYooyYocYYcocYYYcorro.....",
		"....orocYYYcocccccooooorro......",
		".....oroooooccccccccccrro.......",
		"......oorrrrrrrrrrrrrroo........",
		"........oooorrccccrroo..........",
		".........orrccccccccrro.........",
		"........oRrcccYaaYcccrRo........",
		"........oRrccYaaaaYccrRo........",
		"........oRrcccYaaYcccrRo........",
		".........oRrdcdccdcdrRo.........",
		"..........orrdccccdrro..........",
		"...........oorrrrrroo...........",
		"....oooooooaaaooooaaaooooooo....",
		"...obbbbbbbbbbbbbbbbbbbbbbbbo...",
		"...oBBcccccccccccccccccccccco...",
		"...oBBBBBBBBBBBBBBBBBBBBBBBBo...",
		"....oooooooooooooooooooooooo....",
		"................................",
	],
	work2: [
		"................................",
		"........................oo......",
		"........oo.............orRo.....",
		".......oRro............orrRo....",
		"......oRrro..oooooooo..orrrRo...",
		".....oRrrrooorrrrrrrroorrrrRo...",
		".....oRrrrrrrrrrrrrrrrrrrrro....",
		"......orrrrrrrrrrrrrrrrrroo.....",
		".......orrrrrccccccccrrrrro.....",
		"......orroooooccccccccccrrro....",
		".....orrocYYYcocccccooooocrro...",
		".....orroYyyyYoccccocYYYcorro...",
		".....orooYyygoooooooYyyyYorro...",
		".....orroYyyooocaacoYyygoooro...",
		".....orrocYYYcocYYcoYyyooorro...",
		"......orrooooocccccocYYYcoro....",
		".......orrccccccccccoooooro.....",
		"........oorrrrrrrrrrrrrroo......",
		"..........oorrccccrroooo........",
		".........orrccccccccrro.........",
		"........oRrcccYaaYcccrRo........",
		"........oRrccYaaaaYccrRo........",
		"........oRrcccYaaYcccrRo........",
		".........oRrdcdccdcdrRo.........",
		"..........orrdccccdrro..........",
		"...........oorrrrrroo...........",
		"....oooooooaaaooooaaaooooooo....",
		"...obbbbbbbbbbbbbbbbbbbbbbbbo...",
		"...oBBcccccccccccccccccccccco...",
		"...oBBBBBBBBBBBBBBBBBBBBBBBBo...",
		"....oooooooooooooooooooooooo....",
		"................................",
	],
	"work-blink": [
		"................................",
		"......oo........................",
		".....oRro.............oo........",
		"....oRrro............orRo.......",
		"...oRrrro..oooooooo..orrRo......",
		"...oRrrrroorrrrrrrrooorrrRo.....",
		"....orrrrrrrrrrrrrrrrrrrrRo.....",
		".....oorrrrrrrrrrrrrrrrrro......",
		".....orrrrrccccccccrrrrro.......",
		"....orrrccccccccccooooorro......",
		"...orrcooooocccccocccccorro.....",
		"...orrocccccoccccocccccorro.....",
		"...orrocccccoooooooooooooro.....",
		"...oroooooooocaacocccccorro.....",
		"...orrocccccocYYcocccccorro.....",
		"....orocccccocccccooooorro......",
		".....oroooooccccccccccrro.......",
		"......oorrrrrrrrrrrrrroo........",
		"........oooorrccccrroo..........",
		".........orrccccccccrro.........",
		"........oRrcccYaaYcccrRo........",
		"........oRrccYaaaaYccrRo........",
		"........oRrcccYaaYcccrRo........",
		".........oRrdcdccdcdrRo.........",
		"..........orrdccccdrro..........",
		"...........oorrrrrroo...........",
		"....oooooooaaaooooaaaooooooo....",
		"...obbbbbbbbbbbbbbbbbbbbbbbbo...",
		"...oBBcccccccccccccccccccccco...",
		"...oBBBBBBBBBBBBBBBBBBBBBBBBo...",
		"....oooooooooooooooooooooooo....",
		"................................",
	],
	happy: [
		"................................",
		".......oo..............oo.......",
		"......oRro............orRo......",
		".....oRrro............orrRo.....",
		"....oRrrro..oooooooo..orrrRo....",
		"....oRrrrroorrrrrrrroorrrrRo....",
		".....orrrrrrrrrrrrrrrrrrrro.....",
		"......oorrrrrrrrrrrrrrrroo......",
		"......orrrrrccccccccrrrrro......",
		".....orroooooccccccooooorro.....",
		"....orrocccccoccccocccccorro....",
		"....orroccoccooooooccoccorro....",
		"..oooroococococcccocococoorooo..",
		".oRrorroocccoocaacoocccoorrorRo.",
		"oRrrrrrocccccocoococccccorrrrrRo",
		"oRrrrrrroooooccccccooooorrrrrrRo",
		".oRrrrrrrccccccccccccccrrrrrrRo.",
		"..oRrrrrorrrrrrrrrrrrrrorrrrRo..",
		"...oRRrrrooorrccccrrooorrrRRo...",
		"....ooRRrrrrccccccccrrrrRRoo....",
		"......ooRrrcccYaaYcccrrRoo......",
		"........orrccYaaaaYccrro........",
		"........orrcccYaaYcccrro........",
		".........orrdcdccdcdrro.........",
		"..........orrdccccdrro..........",
		"...........oorrrrrroo...........",
		"....oooooooaaaooooaaaooooooo....",
		"...obbbbbbbbbbbbbbbbbbbbbbbbo...",
		"...oBBcccccccccccccccccccccco...",
		"...oBBBBBBBBBBBBBBBBBBBBBBBBo...",
		"....oooooooooooooooooooooooo....",
		"................................",
	],
};

/** Opus's pixel art (palette + poses) for the shared sprite engine. */
export const OPUS_SPRITE: SpriteArt = {
	palette: PALETTE,
	poses: POSES,
};
