/**
 * Sonnet, a 16-bit style pixel-art avatar for Claude Sonnet models.
 *
 * A small, quick wren in three-quarter side view facing right: a plump round
 * body, a short thin beak and the wren's signature tail cocked sharply up at
 * the back. Colored after the Claude palette, with a clay back, wing and tail
 * carrying fine terracotta barring, a cream belly and eyebrow stripe, a big
 * dark eye with a white sparkle and a little blush. It perches on a short twig,
 * and a tiny cream and amber starburst is pinned on its wing.
 *
 * Poses: idle/blink for at rest, work1/work2/work-blink cycled while the agent
 * is streaming (the head dips to peck and the tail flicks), happy briefly when
 * a stream finishes (puffed chest, open beak singing, arc eye, music notes).
 */

import type { PetPose, SpriteArt } from "./sprite";

const PALETTE: Record<string, string> = {
	o: "#3b2a22", // outline (dark brown)
	h: "#d97757", // back, wing and tail (Claude clay)
	H: "#b05a3c", // crown, barring stripes and wing edge (clay shade)
	w: "#e8956f", // back highlight (light clay)
	c: "#f0eee6", // belly, eyebrow stripe, spark core (cream)
	C: "#d9d3c2", // belly shade (warm grey)
	a: "#f0a878", // beak, spark arms, notes (warm amber)
	g: "#ffffff", // eye sparkle
	e: "#2a1a14", // eye (near black brown)
	b: "#f4a090", // blush
	m: "#7a3326", // open beak interior
	l: "#8a6a55", // legs
	t: "#6b4a38", // twig
};

const POSES: Record<PetPose, string[]> = {
	idle: [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"......oooo......................",
		".....oHHHHo........oooo.........",
		".....oHHHHo.......oHHHHo........",
		".....ohhhho......oHHHHHHo.......",
		"......ohhho.....ohhccccchooo....",
		"......oHHHoo....ohhhegehhaaao...",
		".......oHHHHo...ohhceeeccaao....",
		"........ohhhhoo.ohhcbbccCoo.....",
		".........ohhhhhooohccCCCo.......",
		"..........oohhhhhhhhhooo........",
		"..........ohhwwhhcccccco........",
		"..........oHHHhhhccccccco.......",
		".........oHhhhHhcccccccco.......",
		"........ohHHahhhHccccccco.......",
		"........ohHacahhHccccccco.......",
		"........ohHhahhHcccccccCo.......",
		".........ohHhhhHccccccCo........",
		".........ohhHHHccccccCo.........",
		"..........ohhhccccccCo..........",
		"...........ohhCCCCCCo...........",
		"............oolooolo............",
		"..............ll..ll............",
		".......otttlttttlttttlttto......",
		"........ooooooooooooooooo.......",
		"................................",
		"................................",
	],
	blink: [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"......oooo......................",
		".....oHHHHo........oooo.........",
		".....oHHHHo.......oHHHHo........",
		".....ohhhho......oHHHHHHo.......",
		"......ohhho.....ohhccccchooo....",
		"......oHHHoo....ohhhhhhhhaaao...",
		".......oHHHHo...ohhceeeccaao....",
		"........ohhhhoo.ohhcbbccCoo.....",
		".........ohhhhhooohccCCCo.......",
		"..........oohhhhhhhhhooo........",
		"..........ohhwwhhcccccco........",
		"..........oHHHhhhccccccco.......",
		".........oHhhhHhcccccccco.......",
		"........ohHHahhhHccccccco.......",
		"........ohHacahhHccccccco.......",
		"........ohHhahhHcccccccCo.......",
		".........ohHhhhHccccccCo........",
		".........ohhHHHccccccCo.........",
		"..........ohhhccccccCo..........",
		"...........ohhCCCCCCo...........",
		"............oolooolo............",
		"..............ll..ll............",
		".......otttlttttlttttlttto......",
		"........ooooooooooooooooo.......",
		"................................",
		"................................",
	],
	work1: [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"......oooo......................",
		".....oHHHHo........oooo.........",
		".....oHHHHo.......oHHHHo........",
		".....ohhhho......oHHHHHHo.......",
		"......ohhho.....ohhccccchooo....",
		"......oHHHoo....ohhhegehhaaao...",
		".......oHHHHo...ohhceeeccaao....",
		"........ohhhhoo.ohhcbbccCoo.....",
		".........ohhhhhooohccCCCo.......",
		"..........oohhhhhhhhhooo........",
		"..........ohhwwhhcccccco........",
		"..........oHHHhhhccccccco.......",
		".........oHhhhHhcccccccco.......",
		"........ohHHahhhHccccccco.......",
		"........ohHacahhHccccccco.......",
		"........ohHhahhHcccccccCo.......",
		".........ohHhhhHccccccCo........",
		".........ohhHHHccccccCo.........",
		"..........ohhhccccccCo..........",
		"...........ohhCCCCCCo...........",
		"............oolooolo............",
		"..............ll..ll............",
		".......otttlttttlttttlttto......",
		"........ooooooooooooooooo.......",
		"................................",
		"................................",
	],
	work2: [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"....oooo........................",
		"...oHHHHo.......................",
		"...oHHHHo.......................",
		"....ohhhho..........oooo........",
		".....ohhho.........oHHHHo.......",
		"......oHHHoo......oHHHHHHo......",
		".......oHHHHo....ohhcccccho.....",
		"........ohhhhoo..ohhhegehhoo....",
		".........ohhhhhooohhceeeccaao...",
		"..........oohhhhhhhhcbbccCao....",
		"..........ohhwwhhcchccccCooao...",
		"..........oHHHhhhccccccco..o....",
		".........oHhhhHhcccccccco.......",
		"........ohHHahhhHccccccco.......",
		"........ohHacahhHccccccco.......",
		"........ohHhahhHcccccccCo.......",
		".........ohHhhhHccccccCo........",
		".........ohhHHHccccccCo.........",
		"..........ohhhccccccCo..........",
		"...........ohhCCCCCCo...........",
		"............oolooolo............",
		"..............ll..ll............",
		".......otttlttttlttttlttto......",
		"........ooooooooooooooooo.......",
		"................................",
		"................................",
	],
	"work-blink": [
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"......oooo......................",
		".....oHHHHo........oooo.........",
		".....oHHHHo.......oHHHHo........",
		".....ohhhho......oHHHHHHo.......",
		"......ohhho.....ohhccccchooo....",
		"......oHHHoo....ohhhhhhhhaaao...",
		".......oHHHHo...ohhceeeccaao....",
		"........ohhhhoo.ohhcbbccCoo.....",
		".........ohhhhhooohccCCCo.......",
		"..........oohhhhhhhhhooo........",
		"..........ohhwwhhcccccco........",
		"..........oHHHhhhccccccco.......",
		".........oHhhhHhcccccccco.......",
		"........ohHHahhhHccccccco.......",
		"........ohHacahhHccccccco.......",
		"........ohHhahhHcccccccCo.......",
		".........ohHhhhHccccccCo........",
		".........ohhHHHccccccCo.........",
		"..........ohhhccccccCo..........",
		"...........ohhCCCCCCo...........",
		"............oolooolo............",
		"..............ll..ll............",
		".......otttlttttlttttlttto......",
		"........ooooooooooooooooo.......",
		"................................",
		"................................",
	],
	happy: [
		"....................ohho........",
		".....................oho........",
		"....................ooho........",
		"...................ohhho...o....",
		"...................ohho...oao...",
		"....................oo....oao...",
		"......oooo.........oooo..oaao...",
		".....oHHHHo.......oHHHHo.oaao...",
		".....oHHHHo......oHHHHHHo.oo....",
		".....ohhhho.....ohhccccchoo.....",
		"......ohhho.....ohhhhehhoaao....",
		"......oHHHoo....ohhcececcmmo....",
		".......oHHHHo...ohhcbbccCaaao...",
		"........ohhhhoo..ohCCCCCoooo....",
		".........ohhhhhooooooooo........",
		"..........oohhhhhhhhhooo........",
		"..........ohhwwhhccccccco.......",
		"..........oHHHhhhcccccccco......",
		".........oHhhhHhccccccccco......",
		"........ohHHahhhHcccccccco......",
		"........ohHacahhHcccccccco......",
		"........ohHhahhHccccccccCo......",
		".........ohHhhhHccccccCCo.......",
		".........ohhHHHccccccCoo........",
		"..........ohhhccccccCo..........",
		"...........ohhCCCCCCo...........",
		"............oolooolo............",
		"..............ll..ll............",
		".......otttlttttlttttlttto......",
		"........ooooooooooooooooo.......",
		"................................",
		"................................",
	],
};

/** Sonnet's pixel art (palette + poses) for the shared sprite engine. */
export const SONNET_SPRITE: SpriteArt = {
	palette: PALETTE,
	poses: POSES,
};
