#!/usr/bin/env bun
/**
 * build:omp-session — produce the self-contained omp-session binary.
 *
 *   1. `vite build`                    → dist/ (static UI bundle)
 *   2. regenerate server/embedded-dist.ts → one `with { type: "file" }`
 *      import per dist/ asset plus the EMBEDDED_DIST path→file record
 *   3. embed the platform native addon (@oh-my-pi/pi-natives): a tar.gz of
 *      the leaf package's `.node` files + a regenerated `embedded-addon.js`
 *      so the compiled binary can extract and dlopen it (R15: no node_modules
 *      on the sandbox)
 *   4. `Bun.build({ compile, minify, target: "bun" })` → dist-bin/omp-session
 *   5. restore server/embedded-dist.ts and embedded-addon.js to their
 *      originals — always, even on failure; the generated modules only have
 *      meaning inside the compiled binary.
 *
 * Bun 1.3.x quirk: in compile mode the produced executable is named after the
 * entrypoint and `outfile`/`naming` are ignored, so the build lands in
 * dist-bin/ and the produced file is renamed to `omp-session`.
 */

import {
	existsSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	renameSync,
	rmSync,
	statSync,
	writeFileSync,
} from "node:fs";
import { join } from "node:path";
import type { BunPlugin } from "bun";

const STUB = `export const EMBEDDED_DIST: Record<string, string> = {};\n`;
const ROOT = join(import.meta.dir, "..");
const EMBEDDED_DIST_FILE = join(ROOT, "server", "embedded-dist.ts");
const DIST_DIR = join(ROOT, "dist");
const OMP_SESSION_OUTFILE = join(ROOT, "dist-bin", "omp-session");

const NATIVES_PACKAGE_DIR = join(ROOT, "node_modules", "@oh-my-pi", "pi-natives");
const NATIVES_EMBED_FILE = join(NATIVES_PACKAGE_DIR, "native", "embedded-addon.js");

/**
 * The pi-coding-agent SDK lazily `import("omp-legacy-pi-modules")`s a registry
 * of bundled legacy host modules, but only inside compiled binaries — the npm
 * bundle marks it external and dev mode rejects the branch. omp-session drives the
 * modern SDK surface (no legacy Pi extensions), so resolve the specifier to an
 * empty registry rather than bundling the whole legacy host surface.
 */
const legacyPiModulesStub: BunPlugin = {
	name: "omp-session-legacy-pi-modules-stub",
	setup(build) {
		build.onResolve({ filter: /^omp-legacy-pi-modules$/ }, () => ({
			path: "omp-legacy-pi-modules",
			namespace: "omp-session-legacy-pi-stub",
		}));
		build.onLoad({ filter: /.*/, namespace: "omp-session-legacy-pi-stub" }, () => ({
			contents: "export const BUNDLED_PI_MODULE_LOADERS = {};",
			loader: "js",
		}));
	},
};

interface PlatformAddons {
	readonly platformTag: string;
	readonly version: string;
	readonly leafDir: string;
	readonly files: { variant: "modern" | "baseline"; filename: string; size: number }[];
}

/** Locate the build host's pi-natives leaf package (e.g. pi-natives-linux-x64). */
function findPlatformAddons(): PlatformAddons | null {
	const platformTag = `${process.platform}-${process.arch}`;
	const leafDir = join(ROOT, "node_modules", "@oh-my-pi", `pi-natives-${platformTag}`);
	if (!existsSync(leafDir)) return null;
	const manifest = JSON.parse(readFileSync(join(NATIVES_PACKAGE_DIR, "package.json"), "utf8")) as {
		version: string;
	};
	const files: PlatformAddons["files"] = [];
	for (const variant of ["modern", "baseline"] as const) {
		const filename = `pi_natives.${platformTag}-${variant}.node`;
		const path = join(leafDir, filename);
		if (existsSync(path)) files.push({ variant, filename, size: statSync(path).size });
	}
	if (files.length === 0) return null;
	return { platformTag, version: manifest.version, leafDir, files };
}

/**
 * Package the platform addons into a tar.gz and regenerate `embedded-addon.js`
 * so the loader can extract them at runtime. Returns the archive path; the
 * caller restores the original `embedded-addon.js` afterwards.
 */
async function prepareNativeEmbed(addons: PlatformAddons): Promise<string> {
	const archiveFilename = `pi_natives-${addons.platformTag}-${addons.version}.tar.gz`;
	const archivePath = join(NATIVES_PACKAGE_DIR, "native", archiveFilename);
	const archiveSpec = `./${archiveFilename}`;
	await Bun.$`tar -czf ${archivePath} -C ${addons.leafDir} ${addons.files.map((file) => file.filename)}`.cwd(
		ROOT,
	);
	const filesMetadata = addons.files
		.map(
			(file) =>
				`\t{ variant: ${JSON.stringify(file.variant)}, filename: ${JSON.stringify(file.filename)}, size: ${file.size} },`,
		)
		.join("\n");
	const generated =
		`// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY\n// Regenerated by scripts/build-omp-session.ts (Phase 1 packaging)\n\n` +
		`import archiveFile from ${JSON.stringify(archiveSpec)} with { type: "file" };\n\n` +
		`export const embeddedAddon = {\n` +
		`\tplatformTag: ${JSON.stringify(addons.platformTag)},\n` +
		`\tversion: ${JSON.stringify(addons.version)},\n` +
		`\tfiles: [\n${filesMetadata}\n\t],\n` +
		`\tarchive: {\n` +
		`\t\tformat: "tar.gz",\n` +
		`\t\tfilename: ${JSON.stringify(archiveFilename)},\n` +
		`\t\tfilePath: archiveFile,\n` +
		`\t},\n` +
		`};\n`;
	writeFileSync(NATIVES_EMBED_FILE, generated);
	return archivePath;
}

/** Recursively list file paths under `dir`, slash-normalized, relative to `base`. */
function listFiles(dir: string, base: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const abs = join(dir, entry.name);
		if (entry.isDirectory()) out.push(...listFiles(abs, base));
		else if (entry.isFile())
			out.push(
				abs
					.slice(base.length + 1)
					.split("\\")
					.join("/"),
			);
	}
	return out;
}

/** Build the temporary embedded-dist.ts module for the current dist/ contents. */
function generateEmbeddedDist(): string {
	const files = listFiles(DIST_DIR, DIST_DIR)
		.filter((f) => !f.startsWith("."))
		.sort();
	const indexAt = files.indexOf("index.html");
	if (indexAt === -1) {
		throw new Error(`vite build produced no dist/index.html; got: ${files.join(", ")}`);
	}
	const imports = files.map(
		(f, i) => `import f${i} from ${JSON.stringify(`../dist/${f}`)} with { type: "file" };`,
	);
	const entries: string[] = [];
	for (const [i, f] of files.entries()) {
		if (f === "index.html") continue;
		entries.push(`\t${JSON.stringify(`/${f}`)}: f${i},`);
	}
	entries.push(`\t"/": f${indexAt},`);
	entries.push(`\t"/index.html": f${indexAt},`);
	return `${imports.join("\n")}\n\nexport const EMBEDDED_DIST: Record<string, string> = {\n${entries.join("\n")}\n};\n`;
}

let originalEmbeddedAddon: string | null = null;
let addonArchivePath: string | null = null;

try {
	// 1. UI bundle.
	await Bun.$`bunx vite build`.cwd(ROOT);
	// 2. Regenerate the embedded-asset module.
	writeFileSync(EMBEDDED_DIST_FILE, generateEmbeddedDist());
	// 3. Embed the native addon so the binary boots without node_modules (R15).
	const addons = findPlatformAddons();
	if (!addons) {
		throw new Error(
			`no native addon package found for ${process.platform}-${process.arch} ` +
				"(expected node_modules/@oh-my-pi/pi-natives-<platform>); cannot produce a self-contained binary",
		);
	}
	originalEmbeddedAddon = await Bun.file(NATIVES_EMBED_FILE).text();
	addonArchivePath = await prepareNativeEmbed(addons);
	// 4. Compile the daemon with the assets embedded. Bun 1.3.x names the
	//    executable after the entrypoint and ignores `outfile`/`naming` in
	//    compile mode, so build into dist-bin/ and rename the produced file.
	mkdirSync(join(ROOT, "dist-bin"), { recursive: true });
	const build = await Bun.build({
		entrypoints: [join(ROOT, "server", "index.ts")],
		outdir: join(ROOT, "dist-bin"),
		compile: true,
		minify: true,
		target: "bun",
		plugins: [legacyPiModulesStub],
	});
	if (!build.success) {
		throw new Error(build.logs.map((log) => log.message).join("\n"));
	}
	const produced = build.outputs[0]?.path;
	if (!produced) {
		throw new Error("bun build produced no output file");
	}
	if (produced !== OMP_SESSION_OUTFILE) {
		renameSync(produced, OMP_SESSION_OUTFILE);
	}
} finally {
	// 5. Restore the generated modules; they only have meaning inside the
	//    compiled binary.
	writeFileSync(EMBEDDED_DIST_FILE, STUB);
	if (originalEmbeddedAddon !== null) {
		writeFileSync(NATIVES_EMBED_FILE, originalEmbeddedAddon);
	}
	if (addonArchivePath !== null) {
		rmSync(addonArchivePath, { force: true });
	}
}
