/**
 * DeepSeek — 16-bit style pixel-art whale avatar.
 *
 * Sprites are 32x32 ASCII maps over a 16-color palette; render 1px = 1 canvas
 * unit and upscale via CSS (`image-rendering: pixelated`), integer scale only.
 *
 * Poses: idle/blink for at rest, work1/work2/work-blink cycled while the agent
 * is streaming (the spout pulses up and leans between frames), happy briefly
 * when a stream finishes (the spout bursts into droplets and the whale smiles).
 */

import type { PetPose, SpriteArt } from "./sprite";

const PALETTE: Record<string, string> = {
	o: "#141a2e", // outline (deep navy)
	b: "#3361ff", // body (DeepSeek blue)
	B: "#2646c9", // fin (deeper blue)
	l: "#bcd2ff", // belly (light periwinkle)
	w: "#f2f7ff", // eye white
	e: "#232b52", // pupil (deep navy)
	g: "#ffffff", // eye sparkle
	s: "#9fd8ff", // spout water (light blue)
	c: "#35e0d8", // spout droplets / bubble (cyan)
	p: "#ff9eb5", // blush (pink)
};

const POSES: Record<PetPose, string[]> = {
	idle: [
		"................................",
		"................................",
		"..............c...c.............",
		"..............s...s.............",
		".............ssssss.............",
		"..............ssss..............",
		"..............ssss..............",
		"...............ss...............",
		"............oooooooooooo........",
		"..........obbbbbbbbbbbbo........",
		".........obbbbbbbbbbbbbbo.......",
		"........obbbbbbbbbbbbbbbbo......",
		"........obbbbbbbbbbbbbbo..oo....",
		".......obbbbbbbbbbbbbbbboobbo...",
		".......obbbbbbbbbbbbbbbboobbo...",
		"......obbbwwwwwbbbbbbbbbobbbo...",
		"......obbbwgeewbbbbbbbbbobbbo...",
		"......obbbweeewbbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobo.....",
		"......obbbbbbbbbbbbbbbbbobo.....",
		".......obboobbbppbbbbbboobbbo...",
		".......ollllloopplllllloobbo....",
		"........ollloBBollllllo..oo.....",
		"........ollloBBBollllo..........",
		".........ollloBBollo............",
		"..........ollloolo..............",
		"...........oooo.................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
	],
	blink: [
		"................................",
		"................................",
		"..............c...c.............",
		"..............s...s.............",
		".............ssssss.............",
		"..............ssss..............",
		"..............ssss..............",
		"...............ss...............",
		"............oooooooooooo........",
		"..........obbbbbbbbbbbbo........",
		".........obbbbbbbbbbbbbbo.......",
		"........obbbbbbbbbbbbbbbbo......",
		"........obbbbbbbbbbbbbbo..oo....",
		".......obbbbbbbbbbbbbbbboobbo...",
		".......obbbbbbbbbbbbbbbboobbo...",
		"......obbbbbbbbbbbbbbbbbobbbo...",
		"......obbbooooobbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobo.....",
		"......obbbbbbbbbbbbbbbbbobo.....",
		".......obboobbbppbbbbbboobbbo...",
		".......ollllloopplllllloobbo....",
		"........ollloBBollllllo..oo.....",
		"........ollloBBBollllo..........",
		".........ollloBBollo............",
		"..........ollloolo..............",
		"...........oooo.................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
	],
	work1: [
		"................................",
		"................c...............",
		"..............c...c.............",
		"..............s...s.............",
		".............ssssss.............",
		"..............ssss..............",
		"..............ssss..............",
		"...............ss...............",
		"............oooooooooooo........",
		"..........obbbbbbbbbbbbo........",
		".........obbbbbbbbbbbbbbo.......",
		"........obbbbbbbbbbbbbbbbo......",
		"........obbbbbbbbbbbbbbo..oo....",
		".......obbbbbbbbbbbbbbbboobbo...",
		".......obbbbbbbbbbbbbbbboobbo...",
		"......obbbwwwwwbbbbbbbbbobbbo...",
		"......obbbwgeewbbbbbbbbbobbbo...",
		"......obbbweeewbbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobo.....",
		"......obbbbbbbbbbbbbbbbbobo.....",
		".......obboobbbppbbbbbboobbbo...",
		".......ollllloopplllllloobbo....",
		"........ollloBBollllllo..oo.....",
		"........ollloBBBollllo..........",
		".........ollloBBollo............",
		"..........ollloolo..............",
		"...........oooo.................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
	],
	work2: [
		"................................",
		"................................",
		"...............c...c............",
		"...............s...s............",
		"..............sssss.............",
		"...............sss..............",
		"...............sss..............",
		"................ss..............",
		"............oooooooooooo........",
		"..........obbbbbbbbbbbbo........",
		".........obbbbbbbbbbbbbbo.......",
		"........obbbbbbbbbbbbbbbbo......",
		"........obbbbbbbbbbbbbbo..oo....",
		".......obbbbbbbbbbbbbbbboobbo...",
		".......obbbbbbbbbbbbbbbboobbo...",
		"......obbbwwwwwbbbbbbbbbobbbo...",
		"......obbbwgeewbbbbbbbbbobbbo...",
		"......obbbweeewbbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobo.....",
		"......obbbbbbbbbbbbbbbbbobo.....",
		".......obboobbbppbbbbbboobbbo...",
		".......ollllloopplllllloobbo....",
		"........ollloBBollllllo..oo.....",
		"........ollloBBBollllo..........",
		".........ollloBBollo............",
		"..........ollloolo..............",
		"...........oooo.................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
	],
	"work-blink": [
		"................................",
		"................c...............",
		"..............c...c.............",
		"..............s...s.............",
		".............ssssss.............",
		"..............ssss..............",
		"..............ssss..............",
		"...............ss...............",
		"............oooooooooooo........",
		"..........obbbbbbbbbbbbo........",
		".........obbbbbbbbbbbbbbo.......",
		"........obbbbbbbbbbbbbbbbo......",
		"........obbbbbbbbbbbbbbo..oo....",
		".......obbbbbbbbbbbbbbbboobbo...",
		".......obbbbbbbbbbbbbbbboobbo...",
		"......obbbbbbbbbbbbbbbbbobbbo...",
		"......obbbooooobbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobo.....",
		"......obbbbbbbbbbbbbbbbbobo.....",
		".......obboobbbppbbbbbboobbbo...",
		".......ollllloopplllllloobbo....",
		"........ollloBBollllllo..oo.....",
		"........ollloBBBollllo..........",
		".........ollloBBollo............",
		"..........ollloolo..............",
		"...........oooo.................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
	],
	happy: [
		"................................",
		"................................",
		"............cssssssc............",
		"..............ssss..............",
		"..............ssss..............",
		"...............ss...............",
		"................................",
		"................................",
		"............oooooooooooo........",
		"..........obbbbbbbbbbbbo........",
		".........obbbbbbbbbbbbbbo.......",
		"........obbbbbbbbbbbbbbbbo......",
		"........obbbbbbbbbbbbbbo..oo....",
		".......obbbbbbbbbbbbbbbboobbo...",
		".......obbbbbbbbbbbbbbbboobbo...",
		"......obbbbooobbbbbbbbbbobbbo...",
		"......obbbooooobbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobbbo...",
		"......obbbbbbbbbbbbbbbbbobo.....",
		"......obbbbbbbbbbbbbbbbbobo.....",
		".......obboooobppppbbbboobbbo...",
		".......ollllloopppplllloobbo....",
		"........ollloBBollllllo..oo.....",
		"........ollloBBBollllo..........",
		".........ollloBBollo............",
		"..........ollloolo..............",
		"...........oooo.................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
	],
};

export const DEEPSEEK_SPRITE: SpriteArt = {
	palette: PALETTE,
	poses: POSES,
};
