/**
 * Kimi — 16-bit style pixel-art catgirl avatar.
 *
 * Sprites are 32x32 ASCII maps over a 16-color palette; render 1px = 1 canvas
 * unit and upscale via CSS (`image-rendering: pixelated`), integer scale only.
 *
 * Poses: idle/blink for at rest, work1/work2/work-blink cycled while the agent
 * is streaming, happy briefly when a stream finishes.
 */
import { drawSprite, type PetPose, type SpriteArt } from "./sprite";

const PALETTE: Record<string, string> = {
	o: "#2a2333", // outline (dark plum)
	h: "#a8b4f0", // hair base (silver-lavender)
	H: "#7983c9", // hair shadow / tail
	w: "#e4eaff", // hair highlight
	s: "#ffd9c2", // skin
	e: "#2fc4be", // eye iris (teal)
	E: "#146b6d", // eye dark
	g: "#ffffff", // eye sparkle
	p: "#f5a3c0", // inner ear / bow pink
	b: "#ff9eb5", // blush
	m: "#c25a6e", // mouth / bow knot
	d: "#424a75", // outfit (navy)
	D: "#2e3454", // outfit shade
	r: "#e85d75", // bow knot red
};

const POSES: Record<PetPose, string[]> = {
	idle: [
		"................................",
		"........o..............o........",
		".......oho............oho.......",
		"......oppho..........ohppo......",
		"......oppho..........ohppo......",
		".....ohhhhho........ohhhhho.....",
		"......oooooooooooooooooooo......",
		".....owwhhhhhhhhhhhhhhhhwwo.....",
		"....owwhhhhhhhhhhhhhhhhhhwwo....",
		"....ohhhsssssssssssssssshhho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhsssEEEssssssEEEssshho....",
		"....ohhsssgeEssssssEegssshho....",
		"....ohhssseeesssssseeessshho....",
		"....ohhssbbssssssssssbbsshho....",
		"....ohhhsssssssmmssssssshhho....",
		".....ohhsssssssssssssssshho.....",
		".....ohooooooooooooooooooho..oo.",
		"....ohh..odoppprrpppodo..hhooHo.",
		"....ohh..ododpprrppdodo..hhoHHo.",
		"....oh...ododdddddddodo...hoHHo.",
		".........ododdddddddodo...oHHo..",
		".........ododdddddddodo..oHHo...",
		".........osoddddddddosooHHo.....",
		"...........oddddddddooHHo.......",
		"...........oDDDDDDDDooHo........",
		"...........oooooooooo...........",
		"............osso.osso...........",
		"............osso.osso...........",
		"............oooo.oooo...........",
		"................................",
		"................................",
	],
	blink: [
		"................................",
		"........o..............o........",
		".......oho............oho.......",
		"......oppho..........ohppo......",
		"......oppho..........ohppo......",
		".....ohhhhho........ohhhhho.....",
		"......oooooooooooooooooooo......",
		".....owwhhhhhhhhhhhhhhhhwwo.....",
		"....owwhhhhhhhhhhhhhhhhhhwwo....",
		"....ohhhsssssssssssssssshhho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhsssooossssssooossshho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhssbbssssssssssbbsshho....",
		"....ohhhsssssssmmssssssshhho....",
		".....ohhsssssssssssssssshho.....",
		".....ohooooooooooooooooooho..oo.",
		"....ohh..odoppprrpppodo..hhooHo.",
		"....ohh..ododpprrppdodo..hhoHHo.",
		"....oh...ododdddddddodo...hoHHo.",
		".........ododdddddddodo...oHHo..",
		".........ododdddddddodo..oHHo...",
		".........osoddddddddosooHHo.....",
		"...........oddddddddooHHo.......",
		"...........oDDDDDDDDooHo........",
		"...........oooooooooo...........",
		"............osso.osso...........",
		"............osso.osso...........",
		"............oooo.oooo...........",
		"................................",
		"................................",
	],
	work1: [
		"................................",
		"........o..............o........",
		".......oho............oho.......",
		"......oppho..........ohppo......",
		"......oppho..........ohppo......",
		".....ohhhhho........ohhhhho.....",
		"......oooooooooooooooooooo......",
		".....owwhhhhhhhhhhhhhhhhwwo.....",
		"....owwhhhhhhhhhhhhhhhhhhwwo....",
		"....ohhhsssssssssssssssshhho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhsssEEEssssssEEEssshho....",
		"....ohhsssgeEssssssEegssshho....",
		"....ohhssseeesssssseeessshho....",
		"....ohhssbbssssssssssbbsshho....",
		"....ohhhsssssssmmssssssshhho....",
		".....ohhsssssssssssssssshho.....",
		".....ohooooooooooooooooooho..oo.",
		"....ohh..odoppprrpppodo..hhooHo.",
		"....ohh..ododpprrppdodo..hhoHHo.",
		"....oh...ododdddddddodo...hoHHo.",
		".........ododdddddddodo...oHHo..",
		".........ododdddddddodo..oHHo...",
		"...........oddddddddosooHHo.....",
		"...........oddddddddooHHo.......",
		"...........oDDDDDDDDooHo........",
		"...........oooooooooo...........",
		"............osso.osso...........",
		"............osso.osso...........",
		"............oooo.oooo...........",
		"................................",
		"................................",
	],
	work2: [
		"................................",
		"........o..............o........",
		".......oho............oho.......",
		"......oppho..........ohppo......",
		"......oppho..........ohppo......",
		".....ohhhhho........ohhhhho.....",
		"......oooooooooooooooooooo......",
		".....owwhhhhhhhhhhhhhhhhwwo.....",
		"....owwhhhhhhhhhhhhhhhhhhwwo....",
		"....ohhhsssssssssssssssshhho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhsssEEEssssssEEEssshho....",
		"....ohhsssgeEssssssEegssshho....",
		"....ohhssseeesssssseeessshho....",
		"....ohhssbbssssssssssbbsshho....",
		"....ohhhsssssssmmssssssshhho....",
		".....ohhsssssssssssssssshho.....",
		".....ohooooooooooooooooooho.....",
		"....ohh..odoppprrpppodo..hho....",
		"....ohh..ododpprrppdodo..hhoHHo.",
		"....oh...ododdddddddodo...hoHHo.",
		".........ododdddddddodo...oHHo..",
		".........ododdddddddoso..oHHo...",
		".........osoddddddddo..oHHo.....",
		"...........oddddddddooHHo.......",
		"...........oDDDDDDDDooHo........",
		"...........oooooooooo...........",
		"............osso.osso...........",
		"............osso.osso...........",
		"............oooo.oooo...........",
		"................................",
		"................................",
	],
	"work-blink": [
		"................................",
		"........o..............o........",
		".......oho............oho.......",
		"......oppho..........ohppo......",
		"......oppho..........ohppo......",
		".....ohhhhho........ohhhhho.....",
		"......oooooooooooooooooooo......",
		".....owwhhhhhhhhhhhhhhhhwwo.....",
		"....owwhhhhhhhhhhhhhhhhhhwwo....",
		"....ohhhsssssssssssssssshhho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhsssooossssssooossshho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhssbbssssssssssbbsshho....",
		"....ohhhsssssssmmssssssshhho....",
		".....ohhsssssssssssssssshho.....",
		".....ohooooooooooooooooooho..oo.",
		"....ohh..odoppprrpppodo..hhooHo.",
		"....ohh..ododpprrppdodo..hhoHHo.",
		"....oh...ododdddddddodo...hoHHo.",
		".........ododdddddddodo...oHHo..",
		".........ododdddddddodo..oHHo...",
		"...........oddddddddosooHHo.....",
		"...........oddddddddooHHo.......",
		"...........oDDDDDDDDooHo........",
		"...........oooooooooo...........",
		"............osso.osso...........",
		"............osso.osso...........",
		"............oooo.oooo...........",
		"................................",
		"................................",
	],
	happy: [
		"................................",
		"........o..............o........",
		".......oho............oho.......",
		"......oppho..........ohppo......",
		"......oppho..........ohppo......",
		".....ohhhhho........ohhhhho.....",
		"......oooooooooooooooooooo......",
		".....owwhhhhhhhhhhhhhhhhwwo.....",
		"....owwhhhhhhhhhhhhhhhhhhwwo....",
		"....ohhhsssssssssssssssshhho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhssssossssssssosssshho....",
		"....ohhsssosossssssosossshho....",
		"....ohhsssssssssssssssssshho....",
		"....ohhssbbbssssssssbbbsshho....",
		"....ohhhssssssommosssssshhho....",
		".....ohhsssssssssssssssshho.....",
		".....ohooooooooooooooooooho..oo.",
		"....ohh..odoppprrpppodo..hhooHo.",
		"....ohh..ododpprrppdodo..hhoHHo.",
		"....oh...ododdddddddodo...hoHHo.",
		".........ododdddddddodo...oHHo..",
		".........ododdddddddodo..oHHo...",
		".........osoddddddddosooHHo.....",
		"...........oddddddddooHHo.......",
		"...........oDDDDDDDDooHo........",
		"...........oooooooooo...........",
		"............osso.osso...........",
		"............osso.osso...........",
		"............oooo.oooo...........",
		"................................",
		"................................",
	],
};

/** Kimi's pixel art (palette + poses) for the shared sprite engine. */
export const KIMI_SPRITE: SpriteArt = {
	palette: PALETTE,
	poses: POSES,
};

/** Paints `pose` of kimi onto a 32x32 canvas context (clears first). */
export function drawKimi(ctx: CanvasRenderingContext2D, pose: PetPose): void {
	drawSprite(ctx, KIMI_SPRITE, pose);
}
