/**
 * MiniMax — 16-bit style pixel-art "alive" robot avatar, colored after the
 * MiniMax logo (coral #ec5e41 body, MiniMax Crimson #b4393c shade, orange
 * accents) with cyan LED eyes for contrast.
 *
 * Sprites are 32x32 ASCII maps over a 16-color palette; render 1px = 1 canvas
 * unit and upscale via CSS (`image-rendering: pixelated`), integer scale only.
 *
 * Poses: idle/blink for at rest, work1/work2/work-blink cycled while the agent
 * is streaming (the antenna orb, LED eyes and core pulse between frames),
 * happy briefly when a stream finishes (arc eyes, wide smile, full glow).
 */

import type { PetPose, SpriteArt } from "./sprite";
import { drawSprite } from "./sprite";

export type MinimaxPose = PetPose;

const PALETTE: Record<string, string> = {
	o: "#2a2333", // outline (dark plum)
	p: "#ec5e41", // body (logo coral)
	m: "#f0886e", // head highlight (light coral)
	M: "#ff8c42", // mouth / arm tips (orange accent)
	P: "#b4393c", // body shade (MiniMax Crimson)
	v: "#5e2a2a", // visor screen (dark maroon)
	c: "#22d3ee", // LED cyan glow (dim)
	C: "#a5f3fc", // LED cyan glow (bright)
	w: "#ffffff", // eye sparkle
	a: "#fbbf24", // core (amber)
	A: "#fde68a", // core (bright amber)
};

const POSES: Record<MinimaxPose, string[]> = {
	idle: [
		"................................",
		"................................",
		"...............cc...............",
		"...............cc...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"............oooooooo............",
		"..........ommmmmmmmmmo..........",
		".........ommmmmmmmmmmmo.........",
		"........opppppppppppppppo.......",
		"........opppppppppppppppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvwcvvvwcvvppo.......",
		"........oppvvccvvvccvvppo.......",
		"........oppvvvvMMvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........opppppppppppppppo.......",
		".........oppppppppppppo.........",
		".......oMoppppppppppppoMo.......",
		".......oMoppppppppppppoMo.......",
		".........oppppppppppppo.........",
		".........opppppaapppppo.........",
		".........opppppaapppppo.........",
		".........oPPPPPPPPPPPPo.........",
		"..........oPPPPPPPPPPo..........",
		"............oo....oo............",
		"............oo....oo............",
		"................................",
		"................................",
	],
	blink: [
		"................................",
		"................................",
		"...............cc...............",
		"...............cc...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"............oooooooo............",
		"..........ommmmmmmmmmo..........",
		".........ommmmmmmmmmmmo.........",
		"........opppppppppppppppo.......",
		"........opppppppppppppppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvoovvvoovvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvMMvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........opppppppppppppppo.......",
		".........oppppppppppppo.........",
		".......oMoppppppppppppoMo.......",
		".......oMoppppppppppppoMo.......",
		".........oppppppppppppo.........",
		".........opppppaapppppo.........",
		".........opppppaapppppo.........",
		".........oPPPPPPPPPPPPo.........",
		"..........oPPPPPPPPPPo..........",
		"............oo....oo............",
		"............oo....oo............",
		"................................",
		"................................",
	],
	work1: [
		"................................",
		"................................",
		"..............cCCc..............",
		"..............cCCc..............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"............oooooooo............",
		"..........ommmmmmmmmmo..........",
		".........ommmmmmmmmmmmo.........",
		"........opppppppppppppppo.......",
		"........opppppppppppppppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvwCCvvvwCCvppo.......",
		"........oppvCCCvvvCCCvppo.......",
		"........oppvvvvMMvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........opppppppppppppppo.......",
		".........oppppppppppppo.........",
		".......oMoppppppppppppoMo.......",
		".......oMoppppppppppppoMo.......",
		".........opppppaapppppo.........",
		".........opppppAApppppo.........",
		".........opppppAApppppo.........",
		".........oPPPPPaaPPPPPo.........",
		"..........oPPPPPPPPPPo..........",
		"............oo....oo............",
		"............oo....oo............",
		"................................",
		"................................",
	],
	work2: [
		"................................",
		"................................",
		"...............CC...............",
		"...............CC...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"............oooooooo............",
		"..........ommmmmmmmmmo..........",
		".........ommmmmmmmmmmmo.........",
		"........opppppppppppppppo.......",
		"........opppppppppppppppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvwCvvvwCvvppo.......",
		"........oppvvCCvvvCCvvppo.......",
		"........oppvvvvMMvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........opppppppppppppppo.......",
		".........oppppppppppppo.........",
		".......oMoppppppppppppoMo.......",
		".......oMoppppppppppppoMo.......",
		".........oppppppppppppo.........",
		".........opppppAApppppo.........",
		".........opppppAApppppo.........",
		".........oPPPPPPPPPPPPo.........",
		"..........oPPPPPPPPPPo..........",
		"............oo....oo............",
		"............oo....oo............",
		"................................",
		"................................",
	],
	"work-blink": [
		"................................",
		"................................",
		"..............cCCc..............",
		"..............cCCc..............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"............oooooooo............",
		"..........ommmmmmmmmmo..........",
		".........ommmmmmmmmmmmo.........",
		"........opppppppppppppppo.......",
		"........opppppppppppppppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvoovvvoovvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvMMvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........opppppppppppppppo.......",
		".........oppppppppppppo.........",
		".......oMoppppppppppppoMo.......",
		".......oMoppppppppppppoMo.......",
		".........opppppaapppppo.........",
		".........opppppAApppppo.........",
		".........opppppAApppppo.........",
		".........oPPPPPaaPPPPPo.........",
		"..........oPPPPPPPPPPo..........",
		"............oo....oo............",
		"............oo....oo............",
		"................................",
		"................................",
	],
	happy: [
		"................................",
		"................................",
		"..............cCCc..............",
		"..............cCCc..............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"...............oo...............",
		"............oooooooo............",
		"..........ommmmmmmmmmo..........",
		".........ommmmmmmmmmmmo.........",
		"........opppppppppppppppo.......",
		"........opppppppppppppppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........oppvvwvvvvwvvvppo.......",
		"........oppvCCCvvvCCCvppo.......",
		"........oppvvvMMMMvvvvppo.......",
		"........oppvvvvvvvvvvvppo.......",
		"........opppppppppppppppo.......",
		".........oppppppppppppo.........",
		".......oMoppppppppppppoMo.......",
		".......oMoppppppppppppoMo.......",
		".........opppppaapppppo.........",
		".........opppppAApppppo.........",
		".........opppppAApppppo.........",
		".........oPPPPPaaPPPPPo.........",
		"..........oPPPPPPPPPPo..........",
		"............oo....oo............",
		"............oo....oo............",
		"................................",
		"................................",
	],
};

export const MINIMAX_SPRITE: SpriteArt = {
	palette: PALETTE,
	poses: POSES,
};

/** Paints `pose` onto a 32x32 canvas context (clears first). */
export function drawMinimax(ctx: CanvasRenderingContext2D, pose: MinimaxPose): void {
	drawSprite(ctx, MINIMAX_SPRITE, pose);
}
